### PR TITLE
Fixing of a couple things

### PR DESCRIPTION
**Pull request by ellisgl**
Created the 2 missing methods - converted into one, keep it DRY.
Fixed a path to a model.

### CODE REVIEW

**Comment by kerozene** [comment]
Appreciate the PR. Besides the missing methods issue (now fixed by your package.json suggestion), I've also lately fixed (hopefully; this was hard to replicate) the issues with the path to the users (and decks) storage. The users storage is actually a temporary kludge anyway. I mean to replace it with [nedb](https://github.com/louischatriot/nedb).

As for the command prefix discoverability, I think I prefer to use a single prefix in help replies. If there's a discreet but useful way to advertise the other available prefixes I'll do that but this way seems to add a bit too much noise.

**Comment by ellisgl** [comment]
Yeah - that's I close the PR. I figured since you said you used your own version of Node IRC. Also not sure how the hell the the other items got in the pull request....

**Comment by kerozene** [comment]
Heh, fair enough. I forgot to mention btw that the current use of `refreshChanData()` is to query peoples' /away status (for .ping), which can't otherwise be determined (no 'away-notify' on freenode at least).

And I'm on ##humanity-dev on freenode if you want to talk real-time.

**Comment by ellisgl** [comment]
I'm in the channel now.

**Pull request closed without merging**
